# _*_ coding:utf-8 _*_
# Filename: config.py
# Author: pang song
# python 3.6
# Date: 2018/10/11

# 数据接口
# 1.中心显示数据接口
API_URL_CENTER_DISPLAY = "http://www.caiqlab.com:38088/rest/api/unity/center_display"
# 3.设备运行情况接口
API_URL_DEVICE_MONITOR = "http://www.caiqlab.com:38088/rest/api/unity/scatter_display"
# 4.监控覆盖率接口
API_URL_MONITORING_COVERAGE_RATE = "http://www.caiqlab.com:38088/rest/api/unity/monitor_rate_display"
# 5.平均设备使用率接口
API_URL_AVG_DEVICE_USING_RATE = "http://www.caiqlab.com:38088/rest/api/unity/using_rate_display"
# 6.年平均有效机时接口
API_URL_RUNNING_EFFECTIVE_TIME = "http://www.caiqlab.com:38088/rest/api/unity/running_time_display"
# 年共享机时
API_URL_SHARE_SERVICE_TIME = ""

# 备份数据
BACKUP_DATA_CENTER_DISPLAY = [{'监控覆盖率': 46.01}, {'设备使用率': 10.01}]

BACKUP_DATA_MONITORING_COVERAGE_RATE = [
    {'NAME': '农产品中心', 'VALUE': 83.02},
    {'NAME': '陆桥有限', 'VALUE': 0},
    {'NAME': '测评', 'VALUE': 66.67},
    {'NAME': '卫检所', 'VALUE': 48},
    {'NAME': '检测中心', 'VALUE': 48.05},
    {'NAME': '化妆品中心', 'VALUE': 91.67},
    {'NAME': '动检所', 'VALUE': 43.24},
    {'NAME': '工业品所', 'VALUE': 56.9},
    {'NAME': '化学品所', 'VALUE': 37.5},
    {'NAME': 'HACCP中心', 'VALUE': 0},
    {'NAME': '食品所', 'VALUE': 68.97},
    {'NAME': '植检所', 'VALUE': 60},
    {'NAME': '装备所', 'VALUE': 0}]

BACKUP_DATA_AVG_DEVICE_USING_RATE = [
    {'NAME': '农产品中心', 'VALUE': 5.13},
    {'NAME': '测评', 'VALUE': 27.15},
    {'NAME': '卫检所', 'VALUE': 0.6},
    {'NAME': '检测中心', 'VALUE': 9.23},
    {'NAME': '化妆品中心', 'VALUE': 35.54},
    {'NAME': '动检所', 'VALUE': 0.23},
    {'NAME': '工业品所', 'VALUE': 7.03},
    {'NAME': '化学品所', 'VALUE': 4.53},
    {'NAME': '食品所', 'VALUE': 9.33},
    {'NAME': '植检所', 'VALUE': 4.47}]

BACKUP_DATA_RUNNING_EFFECTIVE_TIME = [
    {'NAME': '农产品中心', 'VALUE': 2872},
    {'NAME': '测评', 'VALUE': 1381},
    {'NAME': '卫检所', 'VALUE': 184},
    {'NAME': '检测中心', 'VALUE': 4345},
    {'NAME': '化妆品中心', 'VALUE': 9941},
    {'NAME': '动检所', 'VALUE': 48},
    {'NAME': '工业品所', 'VALUE': 2953},
    {'NAME': '化学品所', 'VALUE': 346},
    {'NAME': '食品所', 'VALUE': 4746},
    {'NAME': '植检所', 'VALUE': 1877}]

BACKUP_DATA_SHARE_SERVICE_TIME = [
    {'NAME': '农产品中心', 'VALUE': 2872},
    {'NAME': '测评', 'VALUE': 1381},
    {'NAME': '卫检所', 'VALUE': 184},
    {'NAME': '检测中心', 'VALUE': 4345},
    {'NAME': '化妆品中心', 'VALUE': 9941},
    {'NAME': '动检所', 'VALUE': 48},
    {'NAME': '工业品所', 'VALUE': 2953},
    {'NAME': '化学品所', 'VALUE': 346},
    {'NAME': '食品所', 'VALUE': 4746},
    {'NAME': '植检所', 'VALUE': 1877}]

BACKUP_DATA_ = [
    {'NAME': 'NextSeq500测序系统', 'VALUE': '-1', 'DEVICE_CODE': '201704000081'} ,
    {'NAME': '个人全基因组测序仪', 'VALUE': '-1', 'DEVICE_CODE': 'ZW14Z007'} ,
    {'NAME': '全自动样品储存管理系统', 'VALUE': '-1', 'DEVICE_CODE': '201704000077'} ,
    {'NAME': '超声波扫描显微镜', 'VALUE': '-1', 'DEVICE_CODE': '201708000048'} ,
    {'NAME': '生物能量代谢分析仪', 'VALUE': '-1', 'DEVICE_CODE': '201608000035'} ,
    {'NAME': '全自动酶标仪', 'VALUE': '-1', 'DEVICE_CODE': 'HX11Z029'} ,
    {'NAME': '全自动样品储存管理系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z025'} ,
    {'NAME': '全自动样品储存管理系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z024'} ,
    {'NAME': '流式细胞仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS12Z095'} ,
    {'NAME': '全自动微生物鉴定仪', 'VALUE': '-1', 'DEVICE_CODE': '201611000030'} ,
    {'NAME': '全自动微生物计数分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201611000024'} ,
    {'NAME': '药敏鉴定系统', 'VALUE': '-1', 'DEVICE_CODE': 'SP11Z039'} ,
    {'NAME': '磁珠纯化仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS13Z008'} ,
    {'NAME': '活体荧光成像系统', 'VALUE': '-1', 'DEVICE_CODE': '201507000026'} ,
    {'NAME': '全自动生化分析仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS09Z077'} ,
    {'NAME': '石墨炉火焰原子吸收光光谱仪', 'VALUE': '-1', 'DEVICE_CODE': '201601003538'} ,
    {'NAME': '氨基酸分析仪', 'VALUE': '1', 'DEVICE_CODE': 'JC12Z022'} ,
    {'NAME': '定量PCR仪', 'VALUE': '-1', 'DEVICE_CODE': 'ZW13Z012'} ,
    {'NAME': '定量PCR仪', 'VALUE': '-1', 'DEVICE_CODE': 'DW12Z034'} ,
    {'NAME': '实时细胞分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201608000435'} ,
    {'NAME': '荧光定量PCR仪', 'VALUE': '-1', 'DEVICE_CODE': '201510000103'} ,
    {'NAME': '中通量测序仪', 'VALUE': '-1', 'DEVICE_CODE': 'ZW14Z006'} ,
    {'NAME': '热重差热比同步分析仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY13Z011'} ,
    {'NAME': '全自动微生物鉴定及药敏分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201511000010'} ,
    {'NAME': '微生物鉴定仪', 'VALUE': '-1', 'DEVICE_CODE': '201603000034'} ,
    {'NAME': '全自动微生物分析系统', 'VALUE': '-1', 'DEVICE_CODE': 'WS06Z044'} ,
    {'NAME': '致病菌荧光免疫分析仪', 'VALUE': '-1', 'DEVICE_CODE': '201608000003'} ,
    {'NAME': '全自动微生物生化鉴定系统', 'VALUE': '1', 'DEVICE_CODE': 'JC12Z031'} ,
    {'NAME': '全自动快速微生物检测系统', 'VALUE': '1', 'DEVICE_CODE': '201511000007'} ,
    {'NAME': '多功能激光扫描成像系统', 'VALUE': '-1', 'DEVICE_CODE': 'DZ09Z079'} ,
    {'NAME': '双向蛋白质电泳系统', 'VALUE': '-1', 'DEVICE_CODE': 'DW12Z046'} ,
    {'NAME': '二维离子色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201807000009'} ,
    {'NAME': '复杂基质中挥发性全组分高分辨鉴定系统', 'VALUE': '1', 'DEVICE_CODE': '201803000043'} ,
    {'NAME': '高分子量有害物质精准筛查系统', 'VALUE': '1', 'DEVICE_CODE': '201803000031'} ,
    {'NAME': '气相色谱-四级杆/静电场轨道阱', 'VALUE': '1', 'DEVICE_CODE': '201803000046'} ,
    {'NAME': '能量色散荧光光谱仪及配套台式计算机1台（DELL GX520）', 'VALUE': '-1', 'DEVICE_CODE': 'JC06Z015'} ,
    {'NAME': '热释光辐照食品X光辐照器', 'VALUE': '-1', 'DEVICE_CODE': 'JC09Z010'} ,
    {'NAME': '线性离子阱-静电场轨道', 'VALUE': '1', 'DEVICE_CODE': '201507000035'} ,
    {'NAME': '超高效液相色谱/多功能色谱仪', 'VALUE': '1', 'DEVICE_CODE': 'SP11Z001'} ,
    {'NAME': '超薄冷冻切片机', 'VALUE': '-1', 'DEVICE_CODE': '201505000039'} ,
    {'NAME': 'ASE快速溶剂萃取仪', 'VALUE': '-1', 'DEVICE_CODE': 'JC08Z004'} ,
    {'NAME': '气相色谱三重四级杆质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': '201511000056'} ,
    {'NAME': '全自动酶标仪', 'VALUE': '-1', 'DEVICE_CODE': 'DZ11Z038'} ,
    {'NAME': '四级杆-静电场轨道阱高分辨液相色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': '201508000058'} ,
    {'NAME': '快速溶剂萃取仪', 'VALUE': '-1', 'DEVICE_CODE': 'JC12Z024'} ,
    {'NAME': '超薄切片机', 'VALUE': '-1', 'DEVICE_CODE': '201602000017'} ,
    {'NAME': '基因测序仪', 'VALUE': '-1', 'DEVICE_CODE': '201603000032'} ,
    {'NAME': '酶标仪', 'VALUE': '-1', 'DEVICE_CODE': 'JC05Z017'} ,
    {'NAME': '高精度有机高分子材料筛查系统', 'VALUE': '-1', 'DEVICE_CODE': '201608000038'} ,
    {'NAME': '离子色谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY09Z021'} ,
    {'NAME': '气相色谱/质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': '201508000101'} ,
    {'NAME': '超高效合相色谱质谱仪', 'VALUE': '1', 'DEVICE_CODE': '201608000046'} ,
    {'NAME': '离子色谱仪', 'VALUE': '-1', 'DEVICE_CODE': '201510000094'} ,
    {'NAME': '高灵敏度高分辨串联色质联用仪', 'VALUE': '1', 'DEVICE_CODE': 'SP13Z008'} ,
    {'NAME': '红外光谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY09Z015'} ,
    {'NAME': '离子色谱仪', 'VALUE': '1', 'DEVICE_CODE': 'JC16L011'} ,
    {'NAME': '离子色谱仪', 'VALUE': '1', 'DEVICE_CODE': 'JC11Z016'} ,
    {'NAME': '气-红外联用仪', 'VALUE': '1', 'DEVICE_CODE': 'SP12Z023'} ,
    {'NAME': '三重四极杆气质联用仪', 'VALUE': '-1', 'DEVICE_CODE': '201704000083'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY06Z016'} ,
    {'NAME': '原子吸收光谱仪', 'VALUE': '1', 'DEVICE_CODE': 'JC08Z001'} ,
    {'NAME': '高压梯度自动纯化系统', 'VALUE': '0', 'DEVICE_CODE': 'WS09Z087'} ,
    {'NAME': '三重四级杆液质联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC13Z027'} ,
    {'NAME': '三重四级杆液质联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC13Z026'} ,
    {'NAME': '气相色谱/质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC06Z009'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'GY06Z015'} ,
    {'NAME': '气相色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201510000022'} ,
    {'NAME': '自动化脂肪酸菌种鉴定系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z042'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': '201510000020'} ,
    {'NAME': '气相色谱仪', 'VALUE': '-1', 'DEVICE_CODE': '201511000094'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'GY06Z017'} ,
    {'NAME': '液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': 'JC06Z008'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': '201601000008'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY08Z004'} ,
    {'NAME': '液相色谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'ZJ12Z040q'} ,
    {'NAME': '气相色谱三重四级杆质谱仪', 'VALUE': '1', 'DEVICE_CODE': '201510000030'} ,
    {'NAME': '原子力显微镜', 'VALUE': '-1', 'DEVICE_CODE': 'GY09Z025'} ,
    {'NAME': '高效液相色谱仪', 'VALUE': '0', 'DEVICE_CODE': '201510000021'} ,
    {'NAME': '气相色谱三重串联四级杆质谱仪', 'VALUE': '1', 'DEVICE_CODE': 'YU11Z013'} ,
    {'NAME': '气相色谱串联质谱仪', 'VALUE': '1', 'DEVICE_CODE': 'JC12Z023'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'DZ09Z082'} ,
    {'NAME': '电感耦合等离子体光谱仪', 'VALUE': '1', 'DEVICE_CODE': 'GY09Z027'} ,
    {'NAME': '液相色谱四级杆飞行时间质谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'SP12Z021'} ,
    {'NAME': '气相色谱-质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': '201508000084'} ,
    {'NAME': '电感耦合等离子体质谱', 'VALUE': '1', 'DEVICE_CODE': 'YU11Z014'} ,
    {'NAME': '电感耦合等离子质谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'SP06Z001'} ,
    {'NAME': '气相色谱/质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC04Z004'} ,
    {'NAME': '液相色谱四级杆飞行时间质谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC13Z012'} ,
    {'NAME': '全自动固相萃取液相串联质谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'SP12Z025'} ,
    {'NAME': '全自动固相萃取液相串联质谱仪', 'VALUE': '0', 'DEVICE_CODE': 'SP12Z024'} ,
    {'NAME': '快速高分离液相色谱四级杆串联质谱仪', 'VALUE': '0', 'DEVICE_CODE': 'SP09Z027'} ,
    {'NAME': '精确质量飞行时间质谱仪', 'VALUE': '1', 'DEVICE_CODE': 'NC14Z005'} ,
    {'NAME': '液相色谱三重串联四级杆质谱仪', 'VALUE': '1', 'DEVICE_CODE': 'YU11Z012'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'YU11Z011'} ,
    {'NAME': '气相色谱质谱联用仪系统', 'VALUE': '-1', 'DEVICE_CODE': 'SP10Z002-2'} ,
    {'NAME': '气相色谱质谱联用仪系统', 'VALUE': '1', 'DEVICE_CODE': 'SP10Z002-1'} ,
    {'NAME': '电感耦合等离子体质谱仪', 'VALUE': '1', 'DEVICE_CODE': 'WS09Z088'} ,
    {'NAME': '600兆核磁共振质谱仪', 'VALUE': '1', 'DEVICE_CODE': '201608000034'} ,
    {'NAME': '气相色谱质谱联用仪系统', 'VALUE': '-1', 'DEVICE_CODE': 'SP13Z006'} ,
    {'NAME': '电感耦合等离子质谱仪', 'VALUE': '1', 'DEVICE_CODE': '201510000043'} ,
    {'NAME': '三重四级杆气质联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC13Z028'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY10Z024'} ,
    {'NAME': '高效液相色谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY07Z001'} ,
    {'NAME': '气相色谱质谱联用仪系统', 'VALUE': '0', 'DEVICE_CODE': '201504000053'} ,
    {'NAME': '气相色谱触角电位联用系统', 'VALUE': '-1', 'DEVICE_CODE': 'DZ09Z095'} ,
    {'NAME': '液质联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC08Z020'} ,
    {'NAME': '多功能自动进样系统', 'VALUE': '-1', 'DEVICE_CODE': 'SP12Z020'} ,
    {'NAME': '高效液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201511000096'} ,
    {'NAME': '悬浮芯片系统', 'VALUE': '-1', 'DEVICE_CODE': 'WS06Z016'} ,
    {'NAME': '数字化痕量分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201505000398'} ,
    {'NAME': '液相芯片检测系统', 'VALUE': '-1', 'DEVICE_CODE': '201611000028'} ,
    {'NAME': '凝胶成像仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS12Z038'} ,
    {'NAME': '蛋白相互作用系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z005'} ,
    {'NAME': '高通量液相芯片平台', 'VALUE': '-1', 'DEVICE_CODE': 'DZ12Z008'} ,
    {'NAME': '液相芯片检测系统', 'VALUE': '-1', 'DEVICE_CODE': '201504000016'} ,
    {'NAME': '液相芯片检测系统', 'VALUE': '-1', 'DEVICE_CODE': 'SP11Z009'} ,
    {'NAME': '凝胶切取系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z015'} ,
    {'NAME': '全自动凝胶切取系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z033'} ,
    {'NAME': '微滴式数字PCR系统', 'VALUE': '-1', 'DEVICE_CODE': '201512000015'} ,
    {'NAME': '全自动酶标仪', 'VALUE': '-1', 'DEVICE_CODE': '201603000028'} ,
    {'NAME': '摩擦试验机', 'VALUE': '-1', 'DEVICE_CODE': '201509000008'} ,
    {'NAME': '微生物快速鉴定与分类系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z006'} ,
    {'NAME': '气相色谱仪', 'VALUE': '-1', 'DEVICE_CODE': '201512000035'} ,
    {'NAME': '基质辅助飞行时间质谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'ZJ12Z041'} ,
    {'NAME': '生物原子力显微镜', 'VALUE': '0', 'DEVICE_CODE': 'WS12Z063'} ,
    {'NAME': '高效液相色谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'SP11Z035'} ,
    {'NAME': '傅里叶变换红外图像系统', 'VALUE': '-1', 'DEVICE_CODE': 'DZ12Z006'} ,
    {'NAME': '傅立叶变换红外图像系统', 'VALUE': '-1', 'DEVICE_CODE': 'ZJ12Z026'} ,
    {'NAME': '扫描探针显微镜', 'VALUE': '-1', 'DEVICE_CODE': 'WS06Z042'} ,
    {'NAME': '定量PCR仪', 'VALUE': '-1', 'DEVICE_CODE': 'DZ12Z022'} ,
    {'NAME': '多重基因表达仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z019'} ,
    {'NAME': '指纹图谱分型系统－基因分析仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z014-1'} ,
    {'NAME': '实时荧光定量PCR仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS13Z014'} ,
    {'NAME': '多重基因表达仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z018'} ,
    {'NAME': 'DNA合成仪', 'VALUE': '0', 'DEVICE_CODE': 'ZJ06Z001'} ,
    {'NAME': '荧光定量PCR仪', 'VALUE': '-1', 'DEVICE_CODE': 'JC12Z016'} ,
    {'NAME': '定量PCR仪', 'VALUE': '-1', 'DEVICE_CODE': 'DZ09Z094'} ,
    {'NAME': '定量PCR仪', 'VALUE': '1', 'DEVICE_CODE': '201608000048'} ,
    {'NAME': '实时荧光PCR仪', 'VALUE': '-1', 'DEVICE_CODE': '201504000020'} ,
    {'NAME': '核酸磁珠处理仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z010-1'} ,
    {'NAME': '自动化胶体金喷金划膜仪', 'VALUE': '-1', 'DEVICE_CODE': '201510000007'} ,
    {'NAME': '物料半自动贴板机', 'VALUE': '-1', 'DEVICE_CODE': '201510000006'} ,
    {'NAME': '全自动蛋白质表达分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201507000106'} ,
    {'NAME': '蛋白定量分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201511000119'} ,
    {'NAME': '全自动酶标仪', 'VALUE': '-1', 'DEVICE_CODE': '201608000047'} ,
    {'NAME': '气体控制扫描探针显微镜', 'VALUE': '-1', 'DEVICE_CODE': '201704000085'} ,
    {'NAME': '超高效液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201705000002'} ,
    {'NAME': '凝胶色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'SP12Z008'} ,
    {'NAME': '全自动细菌鉴定分型溯源系统', 'VALUE': '1', 'DEVICE_CODE': '201511000008'} ,
    {'NAME': '全二维气质联用仪', 'VALUE': '1', 'DEVICE_CODE': 'SP12Z010'} ,
    {'NAME': '气相色谱仪配电子捕获检测器', 'VALUE': '-1', 'DEVICE_CODE': '201508000042'} ,
    {'NAME': '超高效液相色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'YX14Z003'} ,
    {'NAME': '植物活体成像系统', 'VALUE': '-1', 'DEVICE_CODE': 'ZW13Z021'} ,
    {'NAME': '离子迁移谱', 'VALUE': '-1', 'DEVICE_CODE': '201506000034'} ,
    {'NAME': '气味指纹仪电子鼻', 'VALUE': '-1', 'DEVICE_CODE': 'SP11Z036'} ,
    {'NAME': '高速气相色谱指纹分析仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z013'} ,
    {'NAME': '多用途样品前处理平台', 'VALUE': '-1', 'DEVICE_CODE': '201608000299'} ,
    {'NAME': '昆虫神经细胞内记录分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201606000005'} ,
    {'NAME': '高内涵活细胞分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201507000145'} ,
    {'NAME': '全自动样品制备系统', 'VALUE': '-1', 'DEVICE_CODE': '201506000013'} ,
    {'NAME': '石英晶体微量分析仪', 'VALUE': '-1', 'DEVICE_CODE': 'DZ12Z009'} ,
    {'NAME': '皮肤反射光谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY06Z013'} ,
    {'NAME': '激光拉曼光谱仪', 'VALUE': '1', 'DEVICE_CODE': 'GY09Z031'} ,
    {'NAME': '稳定同位素质谱仪', 'VALUE': '1', 'DEVICE_CODE': 'NC12Z022'} ,
    {'NAME': '气相色谱-飞行时间质谱', 'VALUE': '1', 'DEVICE_CODE': 'SP09Z031'} ,
    {'NAME': '实时直接分离离子源', 'VALUE': '-1', 'DEVICE_CODE': 'SP13Z010'} ,
    {'NAME': '全自动激光显微切割系统', 'VALUE': '0', 'DEVICE_CODE': 'DZ09Z041'} ,
    {'NAME': '太阳光模拟仪', 'VALUE': '-1', 'DEVICE_CODE': '201511000289'} ,
    {'NAME': '太阳光模拟仪', 'VALUE': '-1', 'DEVICE_CODE': '201511000290'} ,
    {'NAME': '喷雾干燥仪', 'VALUE': '-1', 'DEVICE_CODE': '201510000015'} ,
    {'NAME': '正置荧光显微镜', 'VALUE': '-1', 'DEVICE_CODE': 'ZW12Z052'} ,
    {'NAME': '微生物基因组测定仪', 'VALUE': '-1', 'DEVICE_CODE': '201603000030'} ,
    {'NAME': '原位电离离子源系统', 'VALUE': '-1', 'DEVICE_CODE': '201803000033'} ,
    {'NAME': '原位检测分析源', 'VALUE': '-1', 'DEVICE_CODE': '201803000025'} ,
    {'NAME': '超临界流体液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201805000033'} ,
    {'NAME': '液相色谱－质谱－质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC12Z042'} ,
    {'NAME': '液相色谱－质谱－质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC12Z041'} ,
    {'NAME': '二维超高效色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201507000096'} ,
    {'NAME': '液相色谱/高分辨飞行时间质联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS08Z054'} ,
    {'NAME': '全自动在线样品处理色谱串联质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': '201504000109'} ,
    {'NAME': '液相/四级杆/飞行时间', 'VALUE': '-1', 'DEVICE_CODE': 'SP08Z006'} ,
    {'NAME': '高效液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201510000032'} ,
    {'NAME': '三重四级杆串联质谱仪', 'VALUE': '1', 'DEVICE_CODE': 'SP07Z005'} ,
    {'NAME': '高通量芯片式分析仪', 'VALUE': '1', 'DEVICE_CODE': '201805000004'} ,
    {'NAME': '三重四级杆串联质谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'JC04Z013'} ,
    {'NAME': '超高效液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': 'JC12Z008'} ,
    {'NAME': '四级杆串联质谱仪', 'VALUE': '0', 'DEVICE_CODE': 'SP08Z007'} ,
    {'NAME': '液相色谱质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'JC04Z006'} ,
    {'NAME': '三重四极杆串联质谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'JC03Z001'} ,
    {'NAME': '三重四级杆串联质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'JC10Z021'} ,
    {'NAME': '超高效液相色谱三重四级杆质谱联用仪', 'VALUE': '1', 'DEVICE_CODE': 'GY09Z030'} ,
    {'NAME': '四级杆离子飞行时间质谱联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY09Z016'} ,
    {'NAME': '超高效液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': 'WS07Z019'} ,
    {'NAME': '高效液相色谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'ZJ06Z002'} ,
    {'NAME': '气相色谱/高分辨飞行时间质联用仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS08Z053'} ,
    {'NAME': '高速老化试验箱', 'VALUE': '-1', 'DEVICE_CODE': 'GY13Z016'} ,
    {'NAME': '多重基因表达分析系统', 'VALUE': '-1', 'DEVICE_CODE': 'ZW12Z048'} ,
    {'NAME': '毛细管电泳仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z027'} ,
    {'NAME': '基因分析仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z004'} ,
    {'NAME': '微量超速离心机', 'VALUE': '0', 'DEVICE_CODE': 'DW12Z033'} ,
    {'NAME': '凯氏定氮仪', 'VALUE': '-1', 'DEVICE_CODE': 'JC10Z009'} ,
    {'NAME': '荧光寿命成像系统', 'VALUE': '-1', 'DEVICE_CODE': 'ZW12Z051'} ,
    {'NAME': '稳态-瞬态荧光光谱仪', 'VALUE': '0', 'DEVICE_CODE': 'GY09Z019'} ,
    {'NAME': '冻干机', 'VALUE': '-1', 'DEVICE_CODE': 'WS09Z021'} ,
    {'NAME': '真空冷冻干燥机', 'VALUE': '-1', 'DEVICE_CODE': 'ZJ12Z021'} ,
    {'NAME': '切条装卡机', 'VALUE': '-1', 'DEVICE_CODE': '201512000037'} ,
    {'NAME': '激光共聚焦显微镜', 'VALUE': '0', 'DEVICE_CODE': 'DZ09Z060'} ,
    {'NAME': '自动原位杂交仪', 'VALUE': '-1', 'DEVICE_CODE': 'DW13Z042'} ,
    {'NAME': '倒置荧光显微镜', 'VALUE': '-1', 'DEVICE_CODE': 'ZJ12Z032'} ,
    {'NAME': '冷冻干燥机', 'VALUE': '-1', 'DEVICE_CODE': 'JC10Z016'} ,
    {'NAME': '蛋白纯化', 'VALUE': '-1', 'DEVICE_CODE': '20061231Z001'} ,
    {'NAME': '定量遗传分析系统', 'VALUE': '0', 'DEVICE_CODE': 'DZ09Z044'} ,
    {'NAME': '微阵列扫描仪', 'VALUE': '-1', 'DEVICE_CODE': 'DZ12Z031'} ,
    {'NAME': '差分离子迁移质量分析仪', 'VALUE': '1', 'DEVICE_CODE': '201806000360'} ,
    {'NAME': '液相色谱-串联四极杆质谱仪', 'VALUE': '1', 'DEVICE_CODE': '201704000058'} ,
    {'NAME': '纳升液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201512000012'} ,
    {'NAME': '生物质谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z026'} ,
    {'NAME': '三重四级杆串联质谱仪和超快速液相色谱仪', 'VALUE': '1', 'DEVICE_CODE': '201608000050'} ,
    {'NAME': '快速高分离液相色谱四级杆串联质谱仪', 'VALUE': '1', 'DEVICE_CODE': 'SP09Z028'} ,
    {'NAME': '超高灵敏度四级杆离子阱分析仪', 'VALUE': '1', 'DEVICE_CODE': 'SP12Z009'} ,
    {'NAME': '四级杆-线性离子阱液质连用系统+在线固相萃取仪', 'VALUE': '1', 'DEVICE_CODE': '201608000045'} ,
    {'NAME': '液相色谱-串联四级杆质谱仪', 'VALUE': '-1', 'DEVICE_CODE': '201704000059'} ,
    {'NAME': '超高效液相色谱/串联四级杆线性离子阱液质联用仪', 'VALUE': '0', 'DEVICE_CODE': 'SP11Z002'} ,
    {'NAME': '表面等离子共振仪', 'VALUE': '-1', 'DEVICE_CODE': 'DZ12Z010'} ,
    {'NAME': '组织细胞毒性扫描系统', 'VALUE': '1', 'DEVICE_CODE': '201612000048'} ,
    {'NAME': '数字PCR系统', 'VALUE': '-1', 'DEVICE_CODE': '201611000020'} ,
    {'NAME': '全自动一体化定量PCR仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS12Z037'} ,
    {'NAME': '多重基因表达谱分析系统', 'VALUE': '-1', 'DEVICE_CODE': '201505000283'} ,
    {'NAME': '核苷酸片段分析系统', 'VALUE': '1', 'DEVICE_CODE': 'ZW12Z049'} ,
    {'NAME': '变性高效液相色谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'SP09Z012'} ,
    {'NAME': '全自动酶标仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS13Z002'} ,
    {'NAME': '微生物生长分析系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z021'} ,
    {'NAME': '微生物基因指纹鉴定系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z032'} ,
    {'NAME': '全自动微生物鉴定仪', 'VALUE': '-1', 'DEVICE_CODE': 'ZJ07Z001'} ,
    {'NAME': '圆二色光谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS12Z118q'} ,
    {'NAME': '氨基酸分析仪', 'VALUE': '1', 'DEVICE_CODE': 'JC13Z011'} ,
    {'NAME': '高解析快速光学成像系统', 'VALUE': '-1', 'DEVICE_CODE': 'GY11Z009'} ,
    {'NAME': '全自动组织成像喷雾系统', 'VALUE': '1', 'DEVICE_CODE': 'ZJ12Z022'} ,
    {'NAME': '凝胶渗透色谱仪', 'VALUE': '1', 'DEVICE_CODE': 'JC13Z007'} ,
    {'NAME': '组织细胞全景显微分析系统', 'VALUE': '-1', 'DEVICE_CODE': 'WS12Z096'} ,
    {'NAME': '倒置荧光显微镜', 'VALUE': '-1', 'DEVICE_CODE': '201507000024'} ,
    {'NAME': '科研级激光扫描共聚焦', 'VALUE': '-1', 'DEVICE_CODE': 'GY12Z005'} ,
    {'NAME': '倒置荧光图像分析', 'VALUE': '-1', 'DEVICE_CODE': '201511000292'} ,
    {'NAME': '凝胶色谱仪', 'VALUE': '-1', 'DEVICE_CODE': 'SP11Z032'} ,
    {'NAME': '气相色谱质谱联用仪', 'VALUE': '0', 'DEVICE_CODE': 'GY09Z028'} ,
    {'NAME': '制备液相色谱', 'VALUE': '-1', 'DEVICE_CODE': 'SP11Z034'} ,
    {'NAME': '全自动蒸馏仪', 'VALUE': '-1', 'DEVICE_CODE': '201803000047'} ,
    {'NAME': '火焰+石墨炉原子吸光光谱仪', 'VALUE': '1', 'DEVICE_CODE': '201508000099'} ,
    {'NAME': '中阶梯光栅-交叉色散全谱直读ICP发光光谱仪', 'VALUE': '1', 'DEVICE_CODE': '201508000100'} ,
    {'NAME': '基因芯片扫描仪', 'VALUE': '-1', 'DEVICE_CODE': 'ZJ07Z003'} ,
    {'NAME': '中阶梯光栅-交叉色散全谱直读ICP发光光谱仪', 'VALUE': '-1', 'DEVICE_CODE': '201611000050'} ,
    {'NAME': '多标记微孔板分析仪', 'VALUE': '-1', 'DEVICE_CODE': 'DZ09Z043'} ,
    {'NAME': '双通道基因芯片扫描仪', 'VALUE': '-1', 'DEVICE_CODE': 'SP04Z001'} ,
    {'NAME': '高通量免疫分析仪', 'VALUE': '-1', 'DEVICE_CODE': 'WS12Z015'} ,
    {'NAME': '液体闪烁计数仪', 'VALUE': '-1', 'DEVICE_CODE': 'GY12Z008'} ,
    {'NAME': '高通量生物大分子分析仪', 'VALUE': '-1', 'DEVICE_CODE': '201507000119'} ,
    {'NAME': '质谱样品预制点靶系统', 'VALUE': '-1', 'DEVICE_CODE': 'NC12Z030'} ,
    {'NAME': '自动化工作站', 'VALUE': '-1', 'DEVICE_CODE': 'WS07Z005'} ,
    {'NAME': '激光共聚焦显微镜', 'VALUE': '-1', 'DEVICE_CODE': '201704000007'}]


# 测试数据
# 部门列表
department_name = [u'食品所',u'植检所',u'动检所',u'卫检所',u'工业品所',u'化学品所',u'装备所',u'农产品中心',u'综合检测中心',u'测试评价中心',u'化妆品中心',u'HACCP中心']
# 监控覆盖率
monitoring_coverage_rate = [79, 90, 90, 90, 44, 63, 67, 77, 88, 90, 12, 83]
# 平均设备使用率
avg_device_using_rate = [79, 90, 90, 90, 44, 63, 67, 77, 88, 90, 12, 83]
# 年有效运行机时
running_effective_time_year = [2179, 5490, 1290, 1690, 2044, 5163, 2167, 2277, 3288, 1090, 4512, 830]
# 年共享机时
shared_service_time_year = [2179, 5490, 1290, 1690, 2044, 5163, 2167, 2277, 3288, 1090, 4512, 830]

pie_data = [[535, u'部门1'],[310, u'部门2'],[234, u'部门3']]

# 设备监控数据，开、关、待机、未部署
device_monitor_data = [{"value":u"0", "name":u"aaa", "device_code": u"ABC001"},
                       {"value":u"1", "name":u"bbb", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"bbb", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"bbb", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"bbb", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"ddd", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"eee", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"1", "name":u"bbb", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"0", "name":u"ccc", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"fff", "device_code": u"ABC002"},
                       {"value":u"2", "name":u"ggg", "device_code": u"ABC002"},
                       {"value":u"3", "name":u"hhh", "device_code": u"ABC003"}]
