# _*_ coding:utf-8 _*_
# Filename: config.py
# Author: pang song
# python 3.6
# Date: 2018/10/11

# 测试数据
# 监控覆盖率

department_name = [u'食品所',u'植检所',u'动检所',u'卫检所',u'工业品所',u'化学品所',u'装备所',u'农产品中心',u'综合检测中心',u'测试评价中心',u'化妆品中心',u'HACCP中心']
monitoring_coverage_rate = [79, 90, 90, 90, 44, 63, 67, 77, 88, 90, 12, 83]
avg_device_using_rate = [79, 90, 90, 90, 44, 63, 67, 77, 88, 90, 12, 83]
running_effective_time_year = [2179, 5490, 1290, 1690, 2044, 5163, 2167, 2277, 3288, 1090, 4512, 830]
shared_service_time_year = [2179, 5490, 1290, 1690, 2044, 5163, 2167, 2277, 3288, 1090, 4512, 830]

pie_data = [[535, u'部门1'],[310, u'部门2'],[234, u'部门3']]


device_monitor_data = [{"value":"0", "name":"aaa", "device_code": "ABC001"},
                       {"value":"1", "name":"bbb", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value": "1", "name": "bbb", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "0", "name": "ccc", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "ddd", "device_code": "ABC002"},
                       {"value": "1", "name": "eee", "device_code": "ABC002"},
                       {"value": "1", "name": "eee", "device_code": "ABC002"},
                       {"value": "1", "name": "eee", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "2", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value": "3", "name": "fff", "device_code": "ABC002"},
                       {"value":"1", "name":"bbb", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"1", "name":"bbb", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"ddd", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"1", "name":"eee", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"1", "name":"bbb", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"0", "name":"ccc", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"3", "name":"fff", "device_code": "ABC002"},
                       {"value":"2", "name":"ggg", "device_code": "ABC002"},
                       {"value":"3", "name":"hhh", "device_code": "ABC003"}]
